use("BaseDatos");

db.Mesa.find({Forma:'Hexagonal'})
db.Mesa.find({Forma:'Cuadrada'})
db.Mesa.find({Estilos:'Rustico'})
db.Mesa.find({Forma:'Elíptica'})
db.Mesa.find({Material:'Marmol'})
db.Mesa.find({Forma:'Circulo incompleto'})
db.Mesa.find({Estilos:''})
db.Mesa.find({Forma:'Trapezoidal'})
db.Mesa.find({Forma:'De forma libre'})
db.Mesa.find({Estilos:'Vintage'})

db.Mueble.find({Material:'Plástico'})
db.Mueble.find({Color:'Blanco'})
db.Mueble.find({Precio:'300'})
db.Mueble.find({Material:'Tela'})
db.Mueble.find({Color:'Blanco'})
db.Mueble.find({Precio:'180'})
db.Mueble.find({Material:'Madera'})
db.Mueble.find({Color:'Nogal'})
db.Mueble.find({Precio:'60'})
db.Mueble.find({Material:'Acero'})

db.Silla.find({Material:'Cuero'})
db.Silla.find({Tamaño:'Grande'})
db.Silla.find({Estilo:'Rustico'})
db.Silla.find({Material:'Ratán'})
db.Silla.find({Tamaño:'Plegable'})
db.Silla.find({Estilo:'Nórdico'})
db.Silla.find({Material:'Vinil'})
db.Silla.find({Tamaño:'Silla de bar'})
db.Silla.find({Estilo:'Minimalista'})
db.Silla.find({Material:'Aluminio'})

db.Sillon.find({Comodidad:'Baja'})
db.Sillon.find({Tamaño:'Grande'})
db.Sillon.find({Color:'Gris'})
db.Sillon.find({Comodidad:'Alta'})
db.Sillon.find({Tamaño:'Pequño'})
db.Sillon.find({Color:'Marrón'})
db.Sillon.find({Comodidad:'Media'})
db.Sillon.find({Tamaño:'Grande'})
db.Sillon.find({Color:'Gris'})
db.Sillon.find({Comodidad:'Baja'})

db.Television.find({Resolucion:'720p'})
db.Television.find({Consumo_de_energía:'180W'})
db.Television.find({Tamaño:'24 pulgadas'})
db.Television.find({Resolucion:'8K'})
db.Television.find({Consumo_de_energía:'120W'})
db.Television.find({Tamaño:'60 pulgadas'})
db.Television.find({Resolucion:'HD'})
db.Television.find({Consumo_de_energía:'130W'})
db.Television.find({Tamaño:'32 pulgadas'})
db.Television.find({Resolucion:'1080p'})



